### ISSUE TITLE
Anyone can invite anyone (including themselves) to an invite-only treasury

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-decide#10]
**Describe the bug**
Anyone can invite anyone to an invite-only treasury, because the account inviting is not verified to be legit participant of the treasury.

**Expected behavior**
Only a member (?) should be able to invite.

**Additional context**
Comment has this issue identified, but not implemented: https://github.com/telosnetwork/telos-decide/blob/b17261e830d2549dfc54e0f9a0e5eb357e5c8a95/contracts/decide/src/voter.cpp#L56

**Comment by craigbranscom** [comment]
Fixed in #17
