### ISSUE TITLE
Voter can prevent token claiming by Treasury Managers

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-decide#5]
**Describe the bug**
Upon claiming tokens from voters by the Treasury Manager, a voter account can have an action dispatcher to assert() during claiming, failing the transaction, and effectively preventing claiming their tokens.

**Expected behavior**
Treasury Manager can claim tokens from a voter.

**Additional context**
The problematic line is here: https://github.com/telosnetwork/telos-decide/blob/b17261e830d2549dfc54e0f9a0e5eb357e5c8a95/contracts/decide/src/treasury.cpp#L259

**Comment by craigbranscom** [comment]
Fixed in PR #17
