### ISSUE TITLE
Liquid TLOS to REX does not count

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-decide#7]
**Describe the bug**
If user works with liquid TLOS (possible scenario if user's intention is to send tokens from an exchange through their account to REX), and never (un)stakes, REX balance is not counted, since the resync function is called only upon staking/unstaking.

This could be solved by making a publicly callable resync() action, and system REX code calling it when TLOS arrives to REX.

**Expected behavior**
User's TLOS in REX should count regardless of staking/unstaking.

**Additional context**
The problematic lines are here: https://github.com/telosnetwork/telos-decide/blob/b17261e830d2549dfc54e0f9a0e5eb357e5c8a95/contracts/decide/include/decide.hpp#L260

**Comment by roger-eosuk** [comment]
Gosh Ville well spotted that man!

**Comment by DouglasHorn** [comment]
This issue was resolved with Telos Decide v2.0.3 Testnet #18 merge
