### ISSUE TITLE
Anyone can steal TLOS deposits from an arbitrary user to fund a treasury

### ISSUE THREAD

**Issue by villesundell** [telosnetwork/telos-decide#9]
**Describe the bug**
User can deposit TLOS to pay for fees, fund a treasury, and stuff.
Problem is, that because of a missing require_auth(), anyone can use anyone's funds to fund a treasury.

**Expected behavior**
Only user themselves should be able fund a treasury from their deposits.

**Additional context**
require_auth() should be placed here: https://github.com/telosnetwork/telos-decide/blob/b17261e830d2549dfc54e0f9a0e5eb357e5c8a95/contracts/decide/src/treasury.cpp#L345

**Comment by craigbranscom** [comment]
Fixed in PR #17
